//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.18444
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using FlapiUnity;
using UnityEngine;
using System.Collections;

public class FlapiIOController : OnlyExpirationInputController
{
	private AudioSource audio;

	public FlapiIOController (ParameterManager parameterManager, DrainageAutogene exercice ,AudioSource audio):base(parameterManager, exercice)
	{
		this.audio = audio;
	}

	public override void Update(){		
		Flapi.Analyze (audio);
	}

	protected override bool isBlowing(){
		return Flapi.blowing;
	}

	public override bool IsMoving ()
	{
		return Input.GetKey (KeyCode.RightArrow);
	}

	public override float GetExpirationStrength(){
		return Flapi.frequency;
	}
}

