//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.18444
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using UnityEngine;

public class DrainageAutogene
{
	private List<Respiration> respirations;
	private int indexRespirationAct;
	private InputState state=InputState.HOLDING_BREATH;
	private InputState lastState=InputState.HOLDING_BREATH;
	private float lastEndVolume = 0.5f;

	/// <summary>
	/// 0 -> Empty lungs
	/// 1 -> Full lungs
	/// </summary>
	private float volume=1.0f;
	//TODO: Make this as a param
	private static float fullExpirationMinTime = 20.0f;
	//TODO: Make this "/2.0f" computed...
	private static float expirationMinTime = fullExpirationMinTime/2.0f;
	private static float expirationSpeed = 1.0f/fullExpirationMinTime;
	
	//TODO: Make this a parameter
	private static float inspirationSpeed=0.5f;
	private static float inspirationMinTime = 1.0f/inspirationSpeed;

	private static float holdingBreathTime=3.0f;

	public DrainageAutogene ()
	{

		respirations = new List<Respiration> (9);
		respirations.Add (new Respiration (0.0f, 1.0f, 0.5f, holdingBreathTime, inspirationSpeed, expirationSpeed));
		respirations.Add (new Respiration (0.5f, 1.0f, 0.5f, holdingBreathTime, inspirationSpeed, expirationSpeed));
		respirations.Add (new Respiration (0.5f, 1.0f, 0.25f, holdingBreathTime, inspirationSpeed, expirationSpeed));
		respirations.Add (new Respiration (0.25f, 0.75f, 0.25f, holdingBreathTime, inspirationSpeed, expirationSpeed));
		respirations.Add (new Respiration (0.25f, 0.75f, 0.25f, holdingBreathTime, inspirationSpeed, expirationSpeed));
		respirations.Add (new Respiration (0.25f, 0.75f, 0.0f, holdingBreathTime, inspirationSpeed, expirationSpeed));
		respirations.Add (new Respiration (0.0f, 0.5f, 0.0f, holdingBreathTime, inspirationSpeed, expirationSpeed));
		respirations.Add (new Respiration (0.0f, 0.5f, 0.0f, holdingBreathTime, inspirationSpeed, expirationSpeed));
		respirations.Add (new Respiration (0.0f, 0.5f, 0.0f, holdingBreathTime, inspirationSpeed, expirationSpeed));
		indexRespirationAct = 0;
	}

	public void CheckProgress(IOController_I ioController){
		lastState = state;
		state = ioController.GetInputState ();

		if (state == InputState.EXPIRATION || state == InputState.STRONG_EXPIRATION) {
			volume-=ioController.GetStrength()*Time.deltaTime*expirationSpeed;
			if(volume<ActualRespiration.EndVolume){
				volume=ActualRespiration.EndVolume;
			}
		}

		if (state == InputState.INSPIRATION) {
			//TODO: Make this "0.5" computed...
			volume+=ioController.GetStrength()*Time.deltaTime*inspirationSpeed;
			if(volume>ActualRespiration.MaxVolume){
				volume=ActualRespiration.MaxVolume;
			}
			if (lastState != state) {
				float volumeExpired=ActualRespiration.MaxVolume-volume;
				float volumeToExpire=ActualRespiration.MaxVolume-ActualRespiration.EndVolume;

				//TODO: Make this 0.75f as parameter
				if(volumeExpired>=0.75f*volumeToExpire){
					indexRespirationAct++;
					indexRespirationAct%=respirations.Count;
				}
			}
		}
	}

	public String GetWarning(){
		float v1=respirations[indexRespirationAct].EndVolume;
		string toReturn=null;

		if (v1 < lastEndVolume) {
			toReturn= "\\/";
		} else if(v1 > lastEndVolume) {
			toReturn= "/\\";
		}
		lastEndVolume = v1;
		return toReturn;
	}

	public Respiration GetActualRespiration(){
		return respirations [indexRespirationAct];
	}
	
	public float ActualMin {
		get{ return this.respirations [this.indexRespirationAct].EndVolume;}
	}
	
	public float ActualMax {
		get{ return this.respirations [this.indexRespirationAct].MaxVolume;}
	}

	public float Volume {
		get{ return this.volume;}
	}

	public Respiration ActualRespiration {
		get{ return respirations [indexRespirationAct];}
	}
	
	public List<Respiration> Respirations {
		get{ return respirations;}
	}
	
	public InputState State {
		get{ return state;}
	}
	
	public float ExpirationSpeed{
		get{ return expirationSpeed;}
	}
		
		
	public float InspirationSpeed{
		get{ return inspirationSpeed;}
	}
}


