//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.18444
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections;

public class Respiration
{
	private float startVolume;
	private float maxVolume;
	private float endVolume;
	private float inspirationTime;

	public Respiration (float startVolume, float maxVolume, float endVolume, float speedInspiration)
		{
		this.startVolume = startVolume;
		this.maxVolume = maxVolume;
		this.endVolume = endVolume;
		this.inspirationTime = (this.maxVolume - this.startVolume)/speedInspiration;
		}

	public float EndVolume {
		get{ return endVolume;}
	}

	public float MaxVolume {
		get{ return maxVolume;}
	}

	public float InspirationTime {
		get { return inspirationTime;}
	}
}

