//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.18444
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections;

public class Respiration
{
	private float startVolume;
	private float maxVolume;
	private float endVolume;
	private float holdingBreathTime;
	private float inspirationTime;
	private float expirationTime;

	public Respiration (float startVolume, float maxVolume, float endVolume, float holdingBreathTime, float inspirationSpeed, float expirationSpeed)
		{
		this.startVolume = startVolume;
		this.maxVolume = maxVolume;
		this.endVolume = endVolume;
		this.holdingBreathTime = holdingBreathTime;
		this.inspirationTime = (this.maxVolume - this.startVolume)/inspirationSpeed;
		this.expirationTime=-(this.endVolume-this.maxVolume)/expirationSpeed;
		}

	public float EndVolume {
		get{ return endVolume;}
	}
	
	public float MaxVolume {
		get{ return maxVolume;}
	}
	
	public float StartVolume {
		get{ return startVolume;}
	}
	
	public float InspirationTime {
		get { return inspirationTime;}
	}
	
	public float ExpirationTime {
		get { return expirationTime;}
	}
	
	public float HoldingBreathTime {
		get { return holdingBreathTime;}
	}
}

