//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.18444
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using UnityEngine;

public class Obstacle : MonoBehaviour
{
	public ObstacleType obstacleType;
	public float minHeight=0;
	public float maxHeight=1;
	public float rarity=1;
	
	public float Rarity{
		get{ return rarity;}
	}
	
	public bool CanBePlaced(float height, ObstacleType type){
		if (this.obstacleType == ObstacleType.BOTH || type == this.obstacleType) {
			return height <= maxHeight && height >= minHeight;
		} else {
			return false;
		}
	}
}

public enum ObstacleType{
	UP,
	DOWN,
	BOTH
}

