//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.18444
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
	
public class ParameterManager
{
	private float strongBreathValue;
	private float inspirationTime;

	public ParameterManager (float strongBreathValue, float inspirationTime)
	{
		this.strongBreathValue = strongBreathValue;
		this.inspirationTime = inspirationTime;
	}
	
	public float StrongBreathValue{
		get{ return strongBreathValue;}
	}
	
	public float InspirationTime{
		get{ return inspirationTime;}
	}

}

